
export const OBTENER_PARTICIPANTES = 'OBTENER_PARTICIPANTES';
export const AÑADIR_PARTICIPANTE = 'AÑADIR_PARTICIPANTE';
export const MODIFICAR_PARTICIPANTE = 'MODIFICAR_PARTICIPANTE';
export const OBTENER_PARTICIPANTES_BY_ID = 'OBTENER_PARTICIPANTES_BY_ID';
export const ELIMINAR_PARTICIPANTE= 'ELIMINAR_PARTICIPANTE';


export const OBTENER_TRABAJOS = 'OBTENER_TRABAJOS';
export const AÑADIR_TRABAJO = 'AÑADIR_TRABAJO';
export const MODIFICAR_TRABAJO = 'MODIFICAR_TRABAJO';
export const ELIMINAR_TRABAJOS = 'ELIMINAR_TRABAJOS';
export const AÑADIR_TRABAJOS = 'AÑADIR_TRABAJOS';
export const MODIFICAR_TRABAJOS = 'MODIFICAR_TRABAJOS';


export const AÑADIR_INTEGRANTES= 'AÑADIR_INTEGRANTES';
export const VINCULAR_INTEGRANTES= 'VINCULAR_INTEGRANTE';
export const ELIMINAR_INTEGRANTES= 'ELIMINAR_INTEGRANTE';
export const VACIAR_INTEGRANTES = 'VACIAR_INTEGRANTES';


export const ABRIR_SELECCIONAR_CREAR = 'ABRIR_SELECCIONAR_CREAR';
export const ABRIR_SELECCIONAR= 'ABRIR_SELECCIONAR';
export const CERRAR_SELECCIONAR= 'CERRAR_SELECCIONAR';


export const ABRIR_MODIFICAR = 'ABRIR_MODIFICAR';
export const CERRAR_MODIFICAR = 'CERRAR_MODIFICAR';
export const TERMINO_BUSQUEDA = 'TERMINO_BUSQUEDA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO= 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR= 'REGISTRO_ERROR';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const OBTENER_USUARIO= 'OBTENER_USUARIO';
export const CERRAR_SESION= 'CERRAR_SESION';



export const TRABAJO_ID= 'TRABAJO_ID';

